#pragma once
#include "ThreadsSharedDataManager.h"
#include "TelemetryPacket.h"
#include "Generals.h"
#include <iostream>

extern std::atomic<bool> g_keep_running_system;

enum class ParserState
{
    WAIT_FOR_SYNC,
    READ_LENGTH,
    READ_PAYLOAD
};

// According to the telemertry-data structure the payload is expected to be 40 bytes + the length of the drone_id string,
// so we can filter corruptions also according to LENGTH value valid range
constexpr int MIN_PAYLOAD_EXP_LENGTH = 40; // bytes
constexpr int MAX_PAYLOAD_EXP_LENGTH = 80; // bytes

class SensorDataConsumer
{
private:
    ThreadsSharedDataManager<BytesArray>& m_shared_raw_data_manager; // the data is a sequence of bytes exactly as they come from the network, shared with class DroneDataSensor
    ThreadsSharedDataManager<TelemetryData>& m_shared_telemetry_packets_manager; // payload-data of parsed valid telemetry packets that found inside the raw bytes sequence
    
    BytesArray m_accumulated_data;
    ParserState m_state;
    uint16_t m_expected_payload_length;

    int m_crc_errors_count;        // counts the cases of Payload or CRC byte corrupted
    int m_invalid_structure_count; // counts the cases Garbage, or corrupted Header/Length leading to loss of sync

    /**
     * Implement a states-machine for extracting valid telemetry packets from the raw bytes sequence received.
     * The state machine's logic handles the following scenarios (that are generated by our 'DroneDataSimulator' logic):
     *      - Packets arriving fragmented across multiple reads
            - Multiple packets arriving in a single buffer
            - Random corrupted bytes within the stream
            - CRC validation failures
            - Loss of synchronization with packet boundaries
     */
    void process_accumulated_data();

    /**
     * Extract the telemetry data from valid packets found in the raw-data buffer, and pack it into a 'TelemetryData' structure for processing in 'TelemetryDataProccessor'
     */
    TelemetryData deserialize_payload(const BytesArray& buffer, size_t start_idx);

public:
    std::vector<BytesArray> valid_packets_received;

    SensorDataConsumer(ThreadsSharedDataManager<BytesArray>& raw_data_manager, 
                       ThreadsSharedDataManager<TelemetryData>& packets_manager);
    void process_loop();
};